# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:16-alpine # smaller & faster (or keep postgres:16 if you want)
    restart: unless-stopped
    environment:
      POSTGRES_USER: scentsational
      POSTGRES_PASSWORD: scentsational
      POSTGRES_DB: scentsational
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '6677:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U scentsational -d scentsational']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
